-- Repairs user_favorites so server/routes/favorites.js can actually write to it.
--
-- The route upserts { user_id, club_id } with onConflict: 'user_id,club_id'. Postgres
-- rejects that when no matching unique constraint exists:
--
--   there is no unique or exclusion constraint matching the ON CONFLICT specification
--
-- which surfaced as a 502, which apiFetch threw, which ClubGrid swallowed into
-- console.error. One of several independent reasons the favorite button did nothing.
--
-- The primary key is on id_of_club, a bigint surrogate row id — not the club id
-- (verified against live data: 12 rows, 12 distinct id_of_club, 9 distinct club_id), so
-- it never constrained the pair.
--
-- Idempotent; safe to re-run.

BEGIN;

-- 1. Drop unusable rows. user_id is nullable, so a favorite belonging to nobody is
--    possible and meaningless. Must happen before the SET NOT NULL at the end.
DELETE FROM user_favorites WHERE user_id IS NULL OR club_id IS NULL;

-- 2. Collapse duplicate pairs — nothing prevented them until now, and the unique
--    constraint below will not apply while any exist. No-op on clean data.
DELETE FROM user_favorites a
USING user_favorites b
WHERE a.user_id = b.user_id
  AND a.club_id = b.club_id
  AND a.ctid > b.ctid;

-- 3. id_of_club is a NOT NULL bigint with no default, and the route never supplies it.
--    If it is not already an identity column then every insert has been failing, so give
--    it a generator and start the sequence above the existing rows.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = 'user_favorites'
      AND column_name  = 'id_of_club'
      AND is_identity  = 'YES'
  ) AND pg_get_serial_sequence('public.user_favorites', 'id_of_club') IS NULL
  THEN
    EXECUTE 'ALTER TABLE user_favorites ALTER COLUMN id_of_club ADD GENERATED BY DEFAULT AS IDENTITY';
    PERFORM setval(
      pg_get_serial_sequence('public.user_favorites', 'id_of_club'),
      COALESCE((SELECT MAX(id_of_club) FROM user_favorites), 0) + 1,
      false
    );
  END IF;
END $$;

-- 4. The constraint the upsert targets.
ALTER TABLE user_favorites
  DROP CONSTRAINT IF EXISTS user_favorites_user_club_unique;

ALTER TABLE user_favorites
  ADD CONSTRAINT user_favorites_user_club_unique UNIQUE (user_id, club_id);

-- 5. user_id defaulted to auth.uid(), a leftover from when the frontend wrote to Supabase
--    directly under RLS. The server connects with the service role now, where auth.uid()
--    is NULL — so any path that omitted user_id would silently insert a null one, and
--    Postgres treats nulls as distinct in UNIQUE, so step 4 would not catch it either.
ALTER TABLE user_favorites ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE user_favorites ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE user_favorites ALTER COLUMN club_id SET NOT NULL;

COMMIT;
